name: cuevaDelRecambio
description: A simple Shop.

version: 0.0.1+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  cloud_firestore: ^3.1.8
  provider: ^6.0.2
  google_sign_in: ^5.3.1
  flutter_facebook_auth: ^4.3.4
  get_it: ^7.2.0
  shared_preferences: ^2.0.15
  shared_preferences_android: ^2.0.12
  firebase_storage: ^10.2.16
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - json/
