on:
  push:
    branches:
      - main
    tags:
      - "v*"

name: 'Code Scan'
jobs:
  build:
    name: Example
    runs-on: ubuntu-latest
    container:
      image: fischerscode/flutter-sudo
    steps:
      - run: sudo su
      - run: git clone https://github.com/alejandrofan2/DAM_TFG
      - run: cd DAM_TFG
      - name: Install dependencies
        run: dart pub get
      - name: Analyze Dart
        uses: zgosalvez/github-actions-analyze-dart@v1