on:
  push:
    branches:
      - main
    tags:
      - "v*"

name: 'Code Scan'
jobs:
  build:
    name: Example
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze Dart
        uses: zgosalvez/github-actions-analyze-dart@v1