on:
  push:
    branches:
      - main
    tags:
      - "v*"

name: 'Code Scan'
jobs:
  build:
    name: Example
    runs-on: ubuntu-latest
    container:
      image: fischerscode/flutter-sudo
    steps:
      - run: sudo su
      - name: Checkout code
        uses: actions/checkout@v2
      - run: exit
      - name: Install dependencies
        run: dart pub get
      - name: Analyze Dart
        uses: zgosalvez/github-actions-analyze-dart@v1