# That code is a GitHub Actions workflow that builds and deploy a
# new build every time we make a commit into main branch.

on:
  push:
    tags:
      - "v*"

name: "Scan and Release"
jobs: 
  scan:
    name: Scan
    runs-on: ubuntu-latest
    container:
      image: fischerscode/flutter-sudo
    steps:
      - name: Clone repo
        run: |
          git clone https://github.com/alejandrofan2/DAM_TFG /home/flutter/DAM_TFG
          sudo chown -R flutter:flutter /home/flutter
          sudo chmod -R 777 /home/flutter
          sudo chmod -R 777 /github
          cd /home/flutter/DAM_TFG
      - name: Install dependencies
        run: |
          cd /home/flutter/DAM_TFG
          flutter pub get
      - name: Analyze Dart
        uses: zgosalvez/github-actions-analyze-dart@v1
        with:
          working-directory: /home/flutter/DAM_TFG
  build:
    name: "Build and release"
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repo
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Setup Flutter
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.0'
      - run: flutter pub get
      - run: flutter build apk --debug --split-per-abi
      - name: "Push to releases"
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*"
          token: ${{ secrets.token }}
